### ISSUE TITLE
Error: Cannot find module './DefaultReplacer'

### ISSUE THREAD

**Issue by kevindenight** [bolasblack/interpolate-webpack-plugin#34]
Require stack:
- /Users/kevindenight/Documents/nut/nutstore-webpages/js_nutflowy/node_modules/@c4605/interpolate-webpack-plugin/lib/index.js
- /Users/kevindenight/Documents/nut/nutstore-webpages/js_nutflowy/configs/webpack.config.ts
- /Users/kevindenight/Documents/nut/nutstore-webpages/js_nutflowy/node_modules/webpack-cli/lib/webpack-cli.js
- /Users/kevindenight/Documents/nut/nutstore-webpages/js_nutflowy/node_modules/webpack-cli/lib/bootstrap.js
- /Users/kevindenight/Documents/nut/nutstore-webpages/js_nutflowy/node_modules/webpack-cli/bin/cli.js
- /Users/kevindenight/Documents/nut/nutstore-webpages/js_nutflowy/node_modules/webpack/bin/webpack.js

Seems like you didn't put DefaultReplacer in lib folder while packaging.

**Comment by kevindenight** [comment]
Reproduced in Version 1.0.1 and 1.0.0 .

**Comment by bolasblack** [comment]
Please take a look at v2.0.1 and feel free to reopen this issue if it remains unresolved.
